[versions]
# استخدم إصدار 8.4.0 ليكون مستقراً مع Gradle الحديث
agp = "8.4.0"
# تحديث الكوتلن إلى 2.0.0 على الأقل لحل مشكلة HasConvention
kotlin = "2.0.0" 
core = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
coroutines = "1.7.3"
lifecycle = "2.6.2"
compress = "1.26.1"
okio = "3.5.0"
retrofit = "2.9.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
apache-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "compress" }
squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
